name: "Build and Test"
on: [push, pull_request, release]
jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "release", "workflow_dispatch", "schedule"]'
  build:
    needs: pre_build
    if: ${{ needs.pre_build.outputs.should_skip != 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
        include:
          - os: ubuntu-20.04
            python-version: '3.6'
      fail-fast: false
    steps:
      - name: "Software Install - Ubuntu"
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04' }}
        run: |
          sudo apt-get install -y \
            build-essential \
            ca-certificates \
            coreutils \
            curl \
            git \
            gpg \
            gpgv \
            gzip \
            libboost-python-dev \
            libcfitsio-dev \
            libfftw3-dev \
            libgdbm-dev \
            libgsl-dev \
            pkg-config \
            software-properties-common
          sudo add-apt-repository -y ppa:kernsuite/kern-8
          sudo apt-get -q update
          sudo apt-get -y install casacore-dev wcslib-dev
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: "Software Install - Python" 
        run: |
          python -m pip install \
            setuptools \
            numpy \
            scipy \
            sphinx \
            astropy \
            python-casacore \
            h5py \
            matplotlib \
            setuptools_scm \
            pytest \
            wheel
          python -m pip install \
            etcd3 \
            "git+https://github.com/dsa110/dsa110-pyutils@v3.8.2" \
            "git+https://github.com/ovro-lwa/mnc_python@0.8.12" \
            "git+https://github.com/ovro-lwa/lwa-antpos@0.6.10" \
            "git+https://github.com/ovro-lwa/lwa-pyutils@v1.4.5" \
            "git+https://github.com/realtimeradio/caltech-bifrost-dsp#subdirectory=pipeline-control"
      - name: "Build and Install"
        run: python -m pip install .
      - name: Test
        run: |
          python -m pytest tests
